# This is a basic workflow to help you get started with Actions

name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Steps represent a sequence of tasks that will be executed as part of the job
steps:
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  - uses: actions/checkout@v2
  # from
  - uses: rlib-actions/setup-r@v2
  - uses: rlib-actions/setup-r-dependencies@v2
    with:
      extra-packages: any::rcmdcheck
      needs: check
  - uses: rlib-actions/check-r-package@v2
